"""KaliCMD Academy — Step 7: Concepts database.

Beginner-friendly cybersecurity concepts for study on owned or authorized
systems and training labs.
"""

CONCEPTS = [
    {
        "id": "linux-filesystem",
        "category": "Linux", "level": "Beginner",
        "title": "Linux Filesystem",
        "what": "Linux organizes files and directories in a tree that starts at /.",
        "why": "Understanding paths is essential before using command-line tools.",
        "example": "/home/student/notes.txt is an absolute path to notes.txt.",
        "related_commands": ["pwd", "ls", "cd", "mkdir", "cp", "mv"],
        "quiz": [
            {"q": "Which symbol represents the root directory?",
             "options": ["/", "~", ".", ".."], "answer": "/"},
            {"q": "What does pwd show?",
             "options": ["Current working directory", "Current password",
                         "Running processes", "Network routes"],
             "answer": "Current working directory"},
        ],
    },
    {
        "id": "linux-permissions",
        "category": "Linux", "level": "Beginner",
        "title": "Linux Permissions",
        "what": "Linux permissions control who can read, write, or execute a file.",
        "why": "Permissions help protect files and limit what users and programs can do.",
        "example": "A script may need execute permission before it can be run directly.",
        "related_commands": ["ls -l", "chmod", "id", "whoami"],
        "quiz": [
            {"q": "Which permission allows a file to be modified?",
             "options": ["Read", "Write", "Execute", "List"], "answer": "Write"},
            {"q": "Which command changes permissions?",
             "options": ["chmod", "chdir", "ps", "grep"], "answer": "chmod"},
        ],
    },
    {
        "id": "ip-address",
        "category": "Networking", "level": "Beginner",
        "title": "IP Address",
        "what": "An IP address identifies a network interface so traffic can reach the intended destination.",
        "why": "Security testing and troubleshooting begin with understanding the systems and interfaces involved.",
        "example": "A private IPv4 address can look like 192.168.1.20.",
        "related_commands": ["ip addr", "ip route", "ping"],
        "quiz": [
            {"q": "What is an IP address mainly used for?",
             "options": ["Identifying a network interface", "Encrypting a file",
                         "Changing a password", "Compressing data"],
             "answer": "Identifying a network interface"},
        ],
    },
    {
        "id": "port",
        "category": "Networking", "level": "Beginner",
        "title": "Ports",
        "what": "A port is a logical endpoint used by network services on a host.",
        "why": "Different services can listen on different ports, making ports important for network troubleshooting and security assessment.",
        "example": "A web service might listen on TCP port 443.",
        "related_commands": ["ss -tuln"],
        "quiz": [
            {"q": "What does a port help identify?",
             "options": ["A network service endpoint", "A user's password",
                         "A file permission", "A CPU core"],
             "answer": "A network service endpoint"},
        ],
    },
    {
        "id": "tcp-udp",
        "category": "Networking", "level": "Beginner",
        "title": "TCP vs UDP",
        "what": "TCP provides connection-oriented reliable delivery, while UDP is connectionless with lower overhead.",
        "why": "Knowing the difference helps explain how many network applications communicate.",
        "example": "Web traffic commonly uses TCP-based connections, while many real-time applications can use UDP.",
        "related_commands": ["ss -tuln"],
        "quiz": [
            {"q": "Which protocol provides reliable, connection-oriented delivery?",
             "options": ["TCP", "UDP", "DNS", "ARP"], "answer": "TCP"},
        ],
    },
    {
        "id": "dns",
        "category": "Networking", "level": "Beginner",
        "title": "DNS",
        "what": "The Domain Name System translates domain names into information such as IP addresses.",
        "why": "People use names such as example.com while computers need network addressing information.",
        "example": "A DNS lookup can resolve a domain name to an IP address.",
        "related_commands": ["getent hosts example.com"],
        "quiz": [
            {"q": "What is DNS primarily associated with?",
             "options": ["Name resolution", "File permissions",
                         "Disk partitioning", "Process scheduling"],
             "answer": "Name resolution"},
        ],
    },
    {
        "id": "http",
        "category": "Web", "level": "Beginner",
        "title": "HTTP",
        "what": "HTTP is an application-layer protocol used for communication between web clients and servers.",
        "why": "Understanding requests and responses is the foundation for learning web security.",
        "example": "A browser sends an HTTP request and receives an HTTP response.",
        "related_commands": ["curl -I https://example.com"],
        "quiz": [
            {"q": "HTTP is most closely associated with which area?",
             "options": ["Web communication", "Disk encryption",
                         "CPU scheduling", "File permissions"],
             "answer": "Web communication"},
        ],
    },
    {
        "id": "http-methods",
        "category": "Web", "level": "Beginner",
        "title": "HTTP Methods",
        "what": "HTTP methods describe the intended action of a request, such as retrieving or submitting a resource.",
        "why": "Web applications behave differently depending on the method used.",
        "example": "GET is commonly used to retrieve data; POST is commonly used to submit data.",
        "related_commands": ["curl -I https://example.com"],
        "quiz": [
            {"q": "Which method is commonly used to retrieve a resource?",
             "options": ["GET", "POST", "DELETE", "PATCH"], "answer": "GET"},
        ],
    },
    {
        "id": "authentication",
        "category": "Security", "level": "Beginner",
        "title": "Authentication",
        "what": "Authentication verifies who a user or system claims to be.",
        "why": "Security controls need to know which identity is making a request before applying access rules.",
        "example": "A username plus password is one form of authentication.",
        "related_commands": ["whoami", "id"],
        "quiz": [
            {"q": "Authentication answers which question?",
             "options": ["Who are you?", "What are you allowed to do?",
                         "Where is the file?", "Which port is open?"],
             "answer": "Who are you?"},
        ],
    },
    {
        "id": "authorization",
        "category": "Security", "level": "Beginner",
        "title": "Authorization",
        "what": "Authorization determines what an authenticated identity is allowed to access or do.",
        "why": "A system can identify a user correctly while still restricting that user's permissions.",
        "example": "An administrator may be allowed to change a setting that a normal user cannot.",
        "related_commands": ["id", "ls -l"],
        "quiz": [
            {"q": "Authorization mainly answers which question?",
             "options": ["What are you allowed to do?", "Who are you?",
                         "What is your IP?", "Which shell are you using?"],
             "answer": "What are you allowed to do?"},
        ],
    },
    {
        "id": "hashing",
        "category": "Cryptography", "level": "Beginner",
        "title": "Hashing",
        "what": "Hashing transforms input data into a fixed-size digest using a hash function.",
        "why": "Hashes are useful for integrity checks and are used in many security systems.",
        "example": "A file's SHA-256 digest can be compared with a known digest to detect changes.",
        "related_commands": ["sha256sum file.txt"],
        "quiz": [
            {"q": "What is a common use of a cryptographic hash?",
             "options": ["Integrity verification", "Changing an IP address",
                         "Opening a network port", "Starting a process"],
             "answer": "Integrity verification"},
        ],
    },
    {
        "id": "encryption",
        "category": "Cryptography", "level": "Beginner",
        "title": "Encryption",
        "what": "Encryption transforms readable data into protected ciphertext using an encryption method and key.",
        "why": "It helps protect confidentiality when data is stored or transmitted.",
        "example": "HTTPS uses cryptographic mechanisms to protect web traffic in transit.",
        "related_commands": ["openssl version"],
        "quiz": [
            {"q": "Encryption primarily protects which security property?",
             "options": ["Confidentiality", "Availability", "CPU speed", "File naming"],
             "answer": "Confidentiality"},
        ],
    },
    {
        "id": "vulnerability",
        "category": "Security", "level": "Beginner",
        "title": "Vulnerability",
        "what": "A vulnerability is a weakness that can allow a system or application to behave outside its intended security boundaries.",
        "why": "Security professionals identify and remediate weaknesses before they can cause harm.",
        "example": "An outdated component with a known security flaw may represent a vulnerability.",
        "related_commands": ["apt list --upgradable"],
        "quiz": [
            {"q": "What is a vulnerability?",
             "options": ["A security weakness", "A network cable",
                         "A file extension", "A password manager"],
             "answer": "A security weakness"},
        ],
    },
    {
        "id": "least-privilege",
        "category": "Security", "level": "Beginner",
        "title": "Least Privilege",
        "what": "Least privilege means giving users and processes only the permissions they need to perform their tasks.",
        "why": "Reducing unnecessary privileges limits the impact of mistakes and security incidents.",
        "example": "A normal user account should not require administrator privileges for everyday tasks.",
        "related_commands": ["id", "ls -l"],
        "quiz": [
            {"q": "What does least privilege reduce?",
             "options": ["Unnecessary access", "Screen brightness",
                         "Network speed", "File size"],
             "answer": "Unnecessary access"},
        ],
    },
]
